### ISSUE TITLE
readFile(path, options) didn't work

### ISSUE THREAD

**Issue by vivaladiem** [finalclass/final-fs#2]
To read text file, I need to specify encoding = 'utf-8'
but it dosen't work.

I think final-fs doesn't pass options to fs.readFile
as I saw source code.

**Comment by finalclass** [comment]
Thankyou for pointing me to a bug.
I've just fixed it. Update the final-fs to version 1.6.1 in which options parameter of readFile is being passed.

**Comment by vivaladiem** [comment]
Thank you:)
